version: "2"
run:
  timeout: 10m
linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - iotamixing
    - misspell
    - modernize
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    staticcheck:
     checks:
       - all
       # Disable QF1008 to retain embedded fields for better readability.
       - "-QF1008"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - sigs.k8s.io/metrics-server
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
