# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud@sha256:ff388e0dc16351e96f8464e2e185b74a7578a5ccb7a112cf3393468e59e6e2d2'
    entrypoint: make
    env:
    - GIT_TAG=$_PULL_BASE_REF
    - GIT_COMMIT=$_PULL_BASE_SHA
    args:
    - push-all
