apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: metrics-server
build:
  local:
    useDockerCLI: true
    useBuildkit: true
  artifacts:
  - image: gcr.io/k8s-staging-metrics-server/metrics-server
    docker:
      dockerfile: Dockerfile
      buildArgs:
        ARCH: "amd64"
        GIT_TAG: "devel"
deploy:
  kustomize:
    paths:
    - manifests/overlays/test
profiles:
  - name: test-ha
    deploy:
      kustomize:
        paths:
        - manifests/overlays/test-ha
  - name: helm
    deploy:
      helm:
        releases:
          - name: metrics-server
            artifactOverrides:
              imageKey: gcr.io/k8s-staging-metrics-server/metrics-server
            chartPath: charts/metrics-server
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO}}"
              image.tag: "{{.IMAGE_TAG}}"
            valuesFiles:
              - charts/metrics-server/ci/ci-values.yaml
