apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: metrics-server
build:
  local:
    useDockerCLI: true
    useBuildkit: true
  artifacts:
  - image: gcr.io/k8s-staging-metrics-server/metrics-server
    docker:
      dockerfile: Dockerfile
      buildArgs:
        ARCH: "amd64"
        GIT_TAG: "devel"
deploy:
  kustomize:
    paths:
    - manifests/test
