apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: metrics-server
build:
  local:
    useDockerCLI: true
    useBuildkit: true
  artifacts:
  - image: gcr.io/k8s-staging-metrics-server/metrics-server
    docker:
      dockerfile: Dockerfile
      buildArgs:
        ARCH: "amd64"
        GIT_TAG: "devel"

profiles:
  - name: test
    deploy:
      kustomize:
        paths:
          - manifests/overlays/test
  - name: test-ha
    deploy:
      kustomize:
        paths:
          - manifests/overlays/test-ha
  - name: helm
    deploy:
      helm:
        releases:
          - name: metrics-server
            namespace: kube-system
            artifactOverrides:
              imageKey: gcr.io/k8s-staging-metrics-server/metrics-server
            chartPath: charts/metrics-server
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO}}"
              image.tag: "{{.IMAGE_TAG}}"
            setValues:
              podLabels: {k8s-app: metrics-server}
              containerPort: 4443
            valuesFiles:
              - charts/metrics-server/ci/ci-values.yaml

