apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
images:
  - name: gcr.io/k8s-staging-metrics-server/metrics-server
    newName: k8s.gcr.io/metrics-server/metrics-server
    newTag: v0.5.0

