apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
- name: kubelet-client-certs
  namespace: kube-system
  files:
  - client.crt=client.crt
  - client.key=client.key
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: metrics-server
    namespace: kube-system
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kubelet-insecure-tls
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kubelet-client-certificate=/certs/client.crt
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kubelet-client-key=/certs/client.key
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --v=4
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --node-selector=metrics-server-skip!=true
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: kubelet-client-certs
        secret:
          secretName: kubelet-client-certs
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: kubelet-client-certs
        mountPath: /certs
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: system:metrics-server
  patch: |
    - op: add
      path: /subjects/-
      value:
        kind: User
        name: metrics-server-client
        apiGroup: rbac.authorization.k8s.io
