{{- if .Values.rbac.create -}}
{{- if .Values.addonResizer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "metrics-server.addonResizer.role" . }}
  namespace: {{ include "metrics-server.namespace" . }}
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  resourceNames:
  - {{ include "metrics-server.fullname" . }}
  verbs:
  - get
  - patch
{{- end -}}
{{- end -}}
