name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - name: Build manifests
        run: make release-manifests
      - name: Release manifests
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v0.1.15
        with:
          files: |
            _output/components.yaml
            _output/high-availability.yaml
            _output/high-availability-1.21+.yaml
      - name: Build binaries
        run: make build-all
      - name: Release binaries
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v0.1.15
        with:
          files: |
            _output/metrics-server-*
